// Login Action Types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// Signup Action Types
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SUCCESS_AUTHENTICATE = "SUCCESS_AUTHENTICATE";
export const AUTHENTICATION_PROGRESS = "AUTHENTICATION_PROGRESS";
export const LOG_OUT = "LOG_OUT";

export const FORM_RESET = "FORM_RESET";
export const FORM_SUBMIT_FAILED = "FORM_SUBMIT_FAILED";
export const FORM_SUBMIT_START = "FORM_SUBMIT_START";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";

export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_SINGLE_STUDENT = "FETCH_SINGLE_STUDENT";
export const REMOVE_SINGLE_STUDENT = "REMOVE_SINGLE_STUDENT";

export const UPDATE_STUDENT_DETAILS_SUCCESS = "UPDATE_STUDENT_DETAILS_SUCCESS";
export const UPDATE_STUDENT_DETAILS_FAIL = "UPDATE_STUDENT_DETAILS_FAIL";
